<?php

use Illuminate\Database\Seeder;

class majors extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('academies')->insert([
            ['academy_name'=>'Khoa Công nghệ'],
            ['academy_name'=>'Khoa Công nghệ Thông tin & Truyền thông'],
            ['academy_name'=>'Khoa Khoa học Chính trị'],
            ['academy_name'=>'Khoa Khoa học Tự nhiên'],
            ['academy_name'=>'Khoa Khoa học Xã hội & Nhân văn'],
            ['academy_name'=>'Khoa Kinh tế'],
            ['academy_name'=>'Khoa Luật'],
            ['academy_name'=>'Khoa Môi trường & Tài nguyên Thiên nhiên'],
            ['academy_name'=>'Khoa Nông nghiệp'],
            ['academy_name'=>'Khoa Sư phạm'],
            ['academy_name'=>'Khoa Thủy sản'],
            // ['academy_name'=>'Khoa Ngoại ngữ'],
            ['academy_name'=>'Khoa Phát triển Nông thôn'],
        ]);
        DB::table('courses')->insert([
            ['course_name'=>'K42'],
            ['course_name'=>'K43'],
            ['course_name'=>'K44'],
            ['course_name'=>'K45']
        ]);
        DB::table('majors')->insert([
            ['academy_id'=>'1',
            'major_name'=>'Công nghệ kỹ thuật hóa học'],
            ['academy_id'=>'1',
            'major_name'=>'Công nghệ kỹ thuật hóa học - CLC'],
            ['academy_id'=>'1',
            'major_name'=>'Kỹ thuật cơ điện tử'],
            ['academy_id'=>'1',
            'major_name'=>'Kỹ thuật cơ khí'],
            ['academy_id'=>'1',
            'major_name'=>'Kỹ thuật điện'],
            ['academy_id'=>'1',
            'major_name'=>'Kỹ thuật điện - CLC'],
            ['academy_id'=>'1',
            'major_name'=>'Kỹ thuật điện tử - viễn thông'],
            ['academy_id'=>'1',
            'major_name'=>'Kỹ thuật điều khiển và tự động hóa'],
            ['academy_id'=>'1',
            'major_name'=>'Kỹ thuật máy tính'],
            ['academy_id'=>'1',
            'major_name'=>'Kỹ thuật xây dựng'],
            ['academy_id'=>'1',
            'major_name'=>'Kỹ thuật xây dựng - CLC'],
            ['academy_id'=>'1',
            'major_name'=>'Kỹ thuật vật liệu'],
            ['academy_id'=>'1',
            'major_name'=>'Kỹ thuật xây dựng công trình giao thông'],
            ['academy_id'=>'1',
            'major_name'=>'Kỹ thuật xây dựng công trình thủy'],
            ['academy_id'=>'1',
            'major_name'=>'Quản lý công nghiệp'],

            ['academy_id'=>'2',
            'major_name'=>'Công nghệ thông tin'],
            ['academy_id'=>'2',
            'major_name'=>'Công nghệ thông tin - CLC'],
            ['academy_id'=>'2',
            'major_name'=>'Hệ thống thông tin'],
            ['academy_id'=>'2',
            'major_name'=>'Khoa học máy tính'],
            ['academy_id'=>'2',
            'major_name'=>'Kỹ thuật phần mềm'],
            ['academy_id'=>'2',
            'major_name'=>'Mạng máy tính và truyền thông dữ liệu'],

            ['academy_id'=>'3',
            'major_name'=>'Chính trị học'],
            ['academy_id'=>'3',
            'major_name'=>'Triết học'],
            
            ['academy_id'=>'4',
            'major_name'=>'Công nghệ sinh học'],
            ['academy_id'=>'4',
            'major_name'=>'Công nghệ sinh học - CLC'],
            ['academy_id'=>'4',
            'major_name'=>'Hóa dược'],
            ['academy_id'=>'4',
            'major_name'=>'Hóa học'],
            ['academy_id'=>'4',
            'major_name'=>'Sinh học'],
            ['academy_id'=>'4',
            'major_name'=>'Toán ứng dụng'],
            ['academy_id'=>'4',
            'major_name'=>'Vật lý kỹ thuật'],

            ['academy_id'=>'5',
            'major_name'=>'Ngôn ngữ Anh'],
            ['academy_id'=>'5',
            'major_name'=>'Ngôn ngữ Anh - CLC'],
            ['academy_id'=>'5',
            'major_name'=>'Ngôn ngữ Pháp'],
            ['academy_id'=>'5',
            'major_name'=>'Thông tin - thư viện'],
            ['academy_id'=>'5',
            'major_name'=>'Văn học'],
            ['academy_id'=>'5',
            'major_name'=>'Việt Nam học'],
            ['academy_id'=>'5',
            'major_name'=>'Xã hội học'],

            ['academy_id'=>'6',
            'major_name'=>'Kế toán'],
            ['academy_id'=>'6',
            'major_name'=>'Kiểm toán'],
            ['academy_id'=>'6',
            'major_name'=>'Kinh doanh quốc tế'],
            ['academy_id'=>'6',
            'major_name'=>'Kinh doanh quốc tế - CLC'],
            ['academy_id'=>'6',
            'major_name'=>'Kinh doanh thương mại'],
            ['academy_id'=>'6',
            'major_name'=>'Kinh tế'],
            ['academy_id'=>'6',
            'major_name'=>'Kinh tế nông nghiệp'],
            ['academy_id'=>'6',
            'major_name'=>'Kinh tế tài nguyên thiên nhiên'],
            ['academy_id'=>'6',
            'major_name'=>'Marketing'],
            ['academy_id'=>'6',
            'major_name'=>'Quản trị dịch vụ du lịch và lữ hành'],
            ['academy_id'=>'6',
            'major_name'=>'Quản trị kinh doanh'],
            ['academy_id'=>'6',
            'major_name'=>'Tài chính - Ngân hàng'],
            ['academy_id'=>'6',
            'major_name'=>'Tài chính - Ngân hàng - CLC'],

            ['academy_id'=>'7',
            'major_name'=>'Luật'],

            ['academy_id'=>'8',
            'major_name'=>'Khoa học môi trường'],
            ['academy_id'=>'8',
            'major_name'=>'Kỹ thuật môi trường'],
            ['academy_id'=>'8',
            'major_name'=>'Quản lý đất đai'],
            ['academy_id'=>'8',
            'major_name'=>'Quản lý tài nguyên và môi trường'],

            ['academy_id'=>'9',
            'major_name'=>'Bảo vệ thực vật'],
            ['academy_id'=>'9',
            'major_name'=>'Chăn nuôi'],
            ['academy_id'=>'9',
            'major_name'=>'Công nghệ sau thu hoạch'],
            ['academy_id'=>'9',
            'major_name'=>'Công nghệ thực phẩm'],
            ['academy_id'=>'9',
            'major_name'=>'Công nghệ thực phẩm - CLC'],
            ['academy_id'=>'9',
            'major_name'=>'Công nghệ rau hoa quả và cảnh quan'],
            ['academy_id'=>'9',
            'major_name'=>'Khoa học cây trồng'],
            ['academy_id'=>'9',
            'major_name'=>'Khoa học đất'],
            ['academy_id'=>'9',
            'major_name'=>'Nông học'],
            ['academy_id'=>'9',
            'major_name'=>'Sinh học ứng dụng'],
            ['academy_id'=>'9',
            'major_name'=>'Thú y'],

            ['academy_id'=>'10',
            'major_name'=>'Giáo dục Công dân'],
            ['academy_id'=>'10',
            'major_name'=>'Giáo dục Thể chất'],
            ['academy_id'=>'10',
            'major_name'=>'Giáo dục Tiểu học'],
            ['academy_id'=>'10',
            'major_name'=>'Sư phạm Địa lý'],
            ['academy_id'=>'10',
            'major_name'=>'Sư phạm Hóa học'],
            ['academy_id'=>'10',
            'major_name'=>'Sư phạm Lịch sử'],
            ['academy_id'=>'10',
            'major_name'=>'Sư phạm Ngữ văn'],
            ['academy_id'=>'10',
            'major_name'=>'Sư phạm Sinh học'],
            ['academy_id'=>'10',
            'major_name'=>'Sư phạm Tin học'],
            ['academy_id'=>'10',
            'major_name'=>'Sư phạm tiếng Anh'],
            ['academy_id'=>'10',
            'major_name'=>'Sư phạm tiếng Pháp'],
            ['academy_id'=>'10',
            'major_name'=>'Sư phạm Toán học'],
            ['academy_id'=>'10',
            'major_name'=>'Sư phạm Vật lý'],

            ['academy_id'=>'11',
            'major_name'=>'Bệnh học thủy sản'],
            ['academy_id'=>'11',
            'major_name'=>'Công nghệ chế biến thủy sản'],
            ['academy_id'=>'11',
            'major_name'=>'Nuôi trồng thủy sản'],
            ['academy_id'=>'11',
            'major_name'=>'Nuôi trồng thủy sản - CLC'],
            ['academy_id'=>'11',
            'major_name'=>'Quản lý thủy sản'],
            
            ['academy_id'=>'12',
            'major_name'=>'Kinh doanh nông nghiệp'],
            ['academy_id'=>'12',
            'major_name'=>'Công nghệ thông tin'],
            ['academy_id'=>'12',
            'major_name'=>'Kinh tế Nông nghiệp'],
            ['academy_id'=>'12',
            'major_name'=>'Kỹ thuật xây dựng'],
            ['academy_id'=>'12',
            'major_name'=>'Luật'],
            ['academy_id'=>'12',
            'major_name'=>'Ngôn ngữ Anh'],
            ['academy_id'=>'12',
            'major_name'=>'uản trị kinh doanh'],
            ['academy_id'=>'12',
            'major_name'=>'Việt Nam học'],
        ]);
    }
}
